//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.ServiceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.proven.cat/", ConfigurationName="ServiceProducto.WSProducto")]
    public interface WSProducto {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/bebidasRequest", ReplyAction="http://services.proven.cat/WSProducto/bebidasResponse")]
        Controlador.ServiceProducto.bebidasResponse bebidas(Controlador.ServiceProducto.bebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/bebidasRequest", ReplyAction="http://services.proven.cat/WSProducto/bebidasResponse")]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.bebidasResponse> bebidasAsync(Controlador.ServiceProducto.bebidasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/pizzasRequest", ReplyAction="http://services.proven.cat/WSProducto/pizzasResponse")]
        Controlador.ServiceProducto.pizzasResponse pizzas(Controlador.ServiceProducto.pizzasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/pizzasRequest", ReplyAction="http://services.proven.cat/WSProducto/pizzasResponse")]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.pizzasResponse> pizzasAsync(Controlador.ServiceProducto.pizzasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/ingredientesRequest", ReplyAction="http://services.proven.cat/WSProducto/ingredientesResponse")]
        Controlador.ServiceProducto.ingredientesResponse ingredientes(Controlador.ServiceProducto.ingredientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/ingredientesRequest", ReplyAction="http://services.proven.cat/WSProducto/ingredientesResponse")]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientesResponse> ingredientesAsync(Controlador.ServiceProducto.ingredientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/ingredientespizzaRequest", ReplyAction="http://services.proven.cat/WSProducto/ingredientespizzaResponse")]
        Controlador.ServiceProducto.ingredientespizzaResponse ingredientespizza(Controlador.ServiceProducto.ingredientespizzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/ingredientespizzaRequest", ReplyAction="http://services.proven.cat/WSProducto/ingredientespizzaResponse")]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientespizzaResponse> ingredientespizzaAsync(Controlador.ServiceProducto.ingredientespizzaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bebidas", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.bebidasRequestBody Body;
        
        public bebidasRequest() {
        }
        
        public bebidasRequest(Controlador.ServiceProducto.bebidasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class bebidasRequestBody {
        
        public bebidasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bebidasResponse", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.bebidasResponseBody Body;
        
        public bebidasResponse() {
        }
        
        public bebidasResponse(Controlador.ServiceProducto.bebidasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bebidasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bebidasResponseBody() {
        }
        
        public bebidasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pizzasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pizzas", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.pizzasRequestBody Body;
        
        public pizzasRequest() {
        }
        
        public pizzasRequest(Controlador.ServiceProducto.pizzasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pizzasRequestBody {
        
        public pizzasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pizzasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pizzasResponse", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.pizzasResponseBody Body;
        
        public pizzasResponse() {
        }
        
        public pizzasResponse(Controlador.ServiceProducto.pizzasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pizzasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public pizzasResponseBody() {
        }
        
        public pizzasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingredientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingredientes", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.ingredientesRequestBody Body;
        
        public ingredientesRequest() {
        }
        
        public ingredientesRequest(Controlador.ServiceProducto.ingredientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ingredientesRequestBody {
        
        public ingredientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingredientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingredientesResponse", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.ingredientesResponseBody Body;
        
        public ingredientesResponse() {
        }
        
        public ingredientesResponse(Controlador.ServiceProducto.ingredientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ingredientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ingredientesResponseBody() {
        }
        
        public ingredientesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingredientespizzaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingredientespizza", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.ingredientespizzaRequestBody Body;
        
        public ingredientespizzaRequest() {
        }
        
        public ingredientespizzaRequest(Controlador.ServiceProducto.ingredientespizzaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ingredientespizzaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long idpizza;
        
        public ingredientespizzaRequestBody() {
        }
        
        public ingredientespizzaRequestBody(long idpizza) {
            this.idpizza = idpizza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingredientespizzaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingredientespizzaResponse", Namespace="http://services.proven.cat/", Order=0)]
        public Controlador.ServiceProducto.ingredientespizzaResponseBody Body;
        
        public ingredientespizzaResponse() {
        }
        
        public ingredientespizzaResponse(Controlador.ServiceProducto.ingredientespizzaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ingredientespizzaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ingredientespizzaResponseBody() {
        }
        
        public ingredientespizzaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProductoChannel : Controlador.ServiceProducto.WSProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProductoClient : System.ServiceModel.ClientBase<Controlador.ServiceProducto.WSProducto>, Controlador.ServiceProducto.WSProducto {
        
        public WSProductoClient() {
        }
        
        public WSProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.ServiceProducto.bebidasResponse Controlador.ServiceProducto.WSProducto.bebidas(Controlador.ServiceProducto.bebidasRequest request) {
            return base.Channel.bebidas(request);
        }
        
        public string bebidas() {
            Controlador.ServiceProducto.bebidasRequest inValue = new Controlador.ServiceProducto.bebidasRequest();
            inValue.Body = new Controlador.ServiceProducto.bebidasRequestBody();
            Controlador.ServiceProducto.bebidasResponse retVal = ((Controlador.ServiceProducto.WSProducto)(this)).bebidas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.bebidasResponse> Controlador.ServiceProducto.WSProducto.bebidasAsync(Controlador.ServiceProducto.bebidasRequest request) {
            return base.Channel.bebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.ServiceProducto.bebidasResponse> bebidasAsync() {
            Controlador.ServiceProducto.bebidasRequest inValue = new Controlador.ServiceProducto.bebidasRequest();
            inValue.Body = new Controlador.ServiceProducto.bebidasRequestBody();
            return ((Controlador.ServiceProducto.WSProducto)(this)).bebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.ServiceProducto.pizzasResponse Controlador.ServiceProducto.WSProducto.pizzas(Controlador.ServiceProducto.pizzasRequest request) {
            return base.Channel.pizzas(request);
        }
        
        public string pizzas() {
            Controlador.ServiceProducto.pizzasRequest inValue = new Controlador.ServiceProducto.pizzasRequest();
            inValue.Body = new Controlador.ServiceProducto.pizzasRequestBody();
            Controlador.ServiceProducto.pizzasResponse retVal = ((Controlador.ServiceProducto.WSProducto)(this)).pizzas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.pizzasResponse> Controlador.ServiceProducto.WSProducto.pizzasAsync(Controlador.ServiceProducto.pizzasRequest request) {
            return base.Channel.pizzasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.ServiceProducto.pizzasResponse> pizzasAsync() {
            Controlador.ServiceProducto.pizzasRequest inValue = new Controlador.ServiceProducto.pizzasRequest();
            inValue.Body = new Controlador.ServiceProducto.pizzasRequestBody();
            return ((Controlador.ServiceProducto.WSProducto)(this)).pizzasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.ServiceProducto.ingredientesResponse Controlador.ServiceProducto.WSProducto.ingredientes(Controlador.ServiceProducto.ingredientesRequest request) {
            return base.Channel.ingredientes(request);
        }
        
        public string ingredientes() {
            Controlador.ServiceProducto.ingredientesRequest inValue = new Controlador.ServiceProducto.ingredientesRequest();
            inValue.Body = new Controlador.ServiceProducto.ingredientesRequestBody();
            Controlador.ServiceProducto.ingredientesResponse retVal = ((Controlador.ServiceProducto.WSProducto)(this)).ingredientes(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientesResponse> Controlador.ServiceProducto.WSProducto.ingredientesAsync(Controlador.ServiceProducto.ingredientesRequest request) {
            return base.Channel.ingredientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientesResponse> ingredientesAsync() {
            Controlador.ServiceProducto.ingredientesRequest inValue = new Controlador.ServiceProducto.ingredientesRequest();
            inValue.Body = new Controlador.ServiceProducto.ingredientesRequestBody();
            return ((Controlador.ServiceProducto.WSProducto)(this)).ingredientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.ServiceProducto.ingredientespizzaResponse Controlador.ServiceProducto.WSProducto.ingredientespizza(Controlador.ServiceProducto.ingredientespizzaRequest request) {
            return base.Channel.ingredientespizza(request);
        }
        
        public string ingredientespizza(long idpizza) {
            Controlador.ServiceProducto.ingredientespizzaRequest inValue = new Controlador.ServiceProducto.ingredientespizzaRequest();
            inValue.Body = new Controlador.ServiceProducto.ingredientespizzaRequestBody();
            inValue.Body.idpizza = idpizza;
            Controlador.ServiceProducto.ingredientespizzaResponse retVal = ((Controlador.ServiceProducto.WSProducto)(this)).ingredientespizza(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientespizzaResponse> Controlador.ServiceProducto.WSProducto.ingredientespizzaAsync(Controlador.ServiceProducto.ingredientespizzaRequest request) {
            return base.Channel.ingredientespizzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.ServiceProducto.ingredientespizzaResponse> ingredientespizzaAsync(long idpizza) {
            Controlador.ServiceProducto.ingredientespizzaRequest inValue = new Controlador.ServiceProducto.ingredientespizzaRequest();
            inValue.Body = new Controlador.ServiceProducto.ingredientespizzaRequestBody();
            inValue.Body.idpizza = idpizza;
            return ((Controlador.ServiceProducto.WSProducto)(this)).ingredientespizzaAsync(inValue);
        }
    }
}
