//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.proven.cat/", ConfigurationName="ServiceReference1.WSProducto")]
    public interface WSProducto {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listAllIngredientsRequest", ReplyAction="http://services.proven.cat/WSProducto/listAllIngredientsResponse")]
        WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse listAllIngredients(WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listAllIngredientsRequest", ReplyAction="http://services.proven.cat/WSProducto/listAllIngredientsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse> listAllIngredientsAsync(WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listIngredientesOfPizzaRequest", ReplyAction="http://services.proven.cat/WSProducto/listIngredientesOfPizzaResponse")]
        WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse listIngredientesOfPizza(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listIngredientesOfPizzaRequest", ReplyAction="http://services.proven.cat/WSProducto/listIngredientesOfPizzaResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse> listIngredientesOfPizzaAsync(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listallpizzasRequest", ReplyAction="http://services.proven.cat/WSProducto/listallpizzasResponse")]
        WindowsFormsApplication1.ServiceReference1.listallpizzasResponse listallpizzas(WindowsFormsApplication1.ServiceReference1.listallpizzasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listallpizzasRequest", ReplyAction="http://services.proven.cat/WSProducto/listallpizzasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallpizzasResponse> listallpizzasAsync(WindowsFormsApplication1.ServiceReference1.listallpizzasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listallbebidasRequest", ReplyAction="http://services.proven.cat/WSProducto/listallbebidasResponse")]
        WindowsFormsApplication1.ServiceReference1.listallbebidasResponse listallbebidas(WindowsFormsApplication1.ServiceReference1.listallbebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.proven.cat/WSProducto/listallbebidasRequest", ReplyAction="http://services.proven.cat/WSProducto/listallbebidasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallbebidasResponse> listallbebidasAsync(WindowsFormsApplication1.ServiceReference1.listallbebidasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listAllIngredientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listAllIngredients", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequestBody Body;
        
        public listAllIngredientsRequest() {
        }
        
        public listAllIngredientsRequest(WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listAllIngredientsRequestBody {
        
        public listAllIngredientsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listAllIngredientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listAllIngredientsResponse", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponseBody Body;
        
        public listAllIngredientsResponse() {
        }
        
        public listAllIngredientsResponse(WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listAllIngredientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listAllIngredientsResponseBody() {
        }
        
        public listAllIngredientsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listIngredientesOfPizzaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listIngredientesOfPizza", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequestBody Body;
        
        public listIngredientesOfPizzaRequest() {
        }
        
        public listIngredientesOfPizzaRequest(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listIngredientesOfPizzaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long idpizza;
        
        public listIngredientesOfPizzaRequestBody() {
        }
        
        public listIngredientesOfPizzaRequestBody(long idpizza) {
            this.idpizza = idpizza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listIngredientesOfPizzaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listIngredientesOfPizzaResponse", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponseBody Body;
        
        public listIngredientesOfPizzaResponse() {
        }
        
        public listIngredientesOfPizzaResponse(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listIngredientesOfPizzaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listIngredientesOfPizzaResponseBody() {
        }
        
        public listIngredientesOfPizzaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listallpizzasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listallpizzas", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listallpizzasRequestBody Body;
        
        public listallpizzasRequest() {
        }
        
        public listallpizzasRequest(WindowsFormsApplication1.ServiceReference1.listallpizzasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listallpizzasRequestBody {
        
        public listallpizzasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listallpizzasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listallpizzasResponse", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listallpizzasResponseBody Body;
        
        public listallpizzasResponse() {
        }
        
        public listallpizzasResponse(WindowsFormsApplication1.ServiceReference1.listallpizzasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listallpizzasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listallpizzasResponseBody() {
        }
        
        public listallpizzasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listallbebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listallbebidas", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listallbebidasRequestBody Body;
        
        public listallbebidasRequest() {
        }
        
        public listallbebidasRequest(WindowsFormsApplication1.ServiceReference1.listallbebidasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listallbebidasRequestBody {
        
        public listallbebidasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listallbebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listallbebidasResponse", Namespace="http://services.proven.cat/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.listallbebidasResponseBody Body;
        
        public listallbebidasResponse() {
        }
        
        public listallbebidasResponse(WindowsFormsApplication1.ServiceReference1.listallbebidasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class listallbebidasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public listallbebidasResponseBody() {
        }
        
        public listallbebidasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProductoChannel : WindowsFormsApplication1.ServiceReference1.WSProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProductoClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.WSProducto>, WindowsFormsApplication1.ServiceReference1.WSProducto {
        
        public WSProductoClient() {
        }
        
        public WSProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse WindowsFormsApplication1.ServiceReference1.WSProducto.listAllIngredients(WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest request) {
            return base.Channel.listAllIngredients(request);
        }
        
        public string listAllIngredients() {
            WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest inValue = new WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequestBody();
            WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listAllIngredients(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse> WindowsFormsApplication1.ServiceReference1.WSProducto.listAllIngredientsAsync(WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest request) {
            return base.Channel.listAllIngredientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listAllIngredientsResponse> listAllIngredientsAsync() {
            WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest inValue = new WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listAllIngredientsRequestBody();
            return ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listAllIngredientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse WindowsFormsApplication1.ServiceReference1.WSProducto.listIngredientesOfPizza(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest request) {
            return base.Channel.listIngredientesOfPizza(request);
        }
        
        public string listIngredientesOfPizza(long idpizza) {
            WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest inValue = new WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequestBody();
            inValue.Body.idpizza = idpizza;
            WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listIngredientesOfPizza(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse> WindowsFormsApplication1.ServiceReference1.WSProducto.listIngredientesOfPizzaAsync(WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest request) {
            return base.Channel.listIngredientesOfPizzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaResponse> listIngredientesOfPizzaAsync(long idpizza) {
            WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest inValue = new WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listIngredientesOfPizzaRequestBody();
            inValue.Body.idpizza = idpizza;
            return ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listIngredientesOfPizzaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.listallpizzasResponse WindowsFormsApplication1.ServiceReference1.WSProducto.listallpizzas(WindowsFormsApplication1.ServiceReference1.listallpizzasRequest request) {
            return base.Channel.listallpizzas(request);
        }
        
        public string listallpizzas() {
            WindowsFormsApplication1.ServiceReference1.listallpizzasRequest inValue = new WindowsFormsApplication1.ServiceReference1.listallpizzasRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listallpizzasRequestBody();
            WindowsFormsApplication1.ServiceReference1.listallpizzasResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listallpizzas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallpizzasResponse> WindowsFormsApplication1.ServiceReference1.WSProducto.listallpizzasAsync(WindowsFormsApplication1.ServiceReference1.listallpizzasRequest request) {
            return base.Channel.listallpizzasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallpizzasResponse> listallpizzasAsync() {
            WindowsFormsApplication1.ServiceReference1.listallpizzasRequest inValue = new WindowsFormsApplication1.ServiceReference1.listallpizzasRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listallpizzasRequestBody();
            return ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listallpizzasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.listallbebidasResponse WindowsFormsApplication1.ServiceReference1.WSProducto.listallbebidas(WindowsFormsApplication1.ServiceReference1.listallbebidasRequest request) {
            return base.Channel.listallbebidas(request);
        }
        
        public string listallbebidas() {
            WindowsFormsApplication1.ServiceReference1.listallbebidasRequest inValue = new WindowsFormsApplication1.ServiceReference1.listallbebidasRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listallbebidasRequestBody();
            WindowsFormsApplication1.ServiceReference1.listallbebidasResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listallbebidas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallbebidasResponse> WindowsFormsApplication1.ServiceReference1.WSProducto.listallbebidasAsync(WindowsFormsApplication1.ServiceReference1.listallbebidasRequest request) {
            return base.Channel.listallbebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.listallbebidasResponse> listallbebidasAsync() {
            WindowsFormsApplication1.ServiceReference1.listallbebidasRequest inValue = new WindowsFormsApplication1.ServiceReference1.listallbebidasRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.listallbebidasRequestBody();
            return ((WindowsFormsApplication1.ServiceReference1.WSProducto)(this)).listallbebidasAsync(inValue);
        }
    }
}
